### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by barrett092** [CenturionInfoSec/pstoken-burp-plugin#2]
Getting a plethora of python errors - not sure if this plugin is still supported...

**Comment by ryanbaxendale** [comment]
did you install jython https://portswigger.net/burp/documentation/desktop/extensions/installing-extensions#installing-jython-or-jruby and then load the plugin?

please provide more information

**Comment by barrett092** [comment]
Sure - I've tried a few different version of Jython. I mainly get these traceback errors:

Traceback (most recent call last):
  File "/Users/skynet/.BurpSuite/bapps/df04d7d1af004ed6b50c555c4920232d/pstoken.py", line 98, in generateToken
    endianVal = int(tmp4.getText())
ValueError: invalid literal for int() with base 10: 'tmp'

(Generating Token)

Traceback (most recent call last):
  File "/Users/skynet/.BurpSuite/bapps/df04d7d1af004ed6b50c555c4920232d/pstoken.py", line 50, in decodeData
    data=zlib.decompress( inflate_data )
  File "/Users/skynet/Downloads/jython-standalone-2.7.2.jar/Lib/zlib$py.class", line 93, in decompress
  File "/Users/skynet/Downloads/jython-standalone-2.7.2.jar/Lib/zlib$py.class", line 293, in _get_inflate_data
zlib.error: java.util.zip.DataFormatException: incorrect header check

(Decoding Token)

**Comment by ryanbaxendale** [comment]
it works with burp v2023.11.1.3 and jython standalone 2.7.2 and 2.7.3
you need to enter **only** the cookie value (base64 as "pAAA....=") in the input box "PS_TOKEN Cookie" then click "decode"
once you crack the hash enter the password in "node password" then click "generate" to get the new cookie
